print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print('Balson')
print('Webb')
print("India")
print("I am enjoying 30 days of python")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['A','B','C']))
print(type('Balson'))
print(type('My country name is India'))
